DROP TABLE IF EXISTS TBL_CLIENTES;
 
CREATE TABLE TBL_CLIENTES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  sobrenome VARCHAR(100) NOT NULL,
  brinquedo VARCHAR(50) NOT NULL,
  email VARCHAR(100) DEFAULT NULL
);